courses/urls.py
from django.urls import path

from . import views

app_name = "courses"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:courses_id>", views.register, name="register"),
    path("mycourses", views.mycourses, name="mycourses"),
    path("coursesinfo/<int:courses_id>", views.coursesinfo, name="coursesinfo"),
    path("confirm", views.confirm, name="confirm"),
    path("remove/<int:courses_id>", views.remove, name="remove"),
    path("admin", views.admin, name="admin"),
    path("admininfo/<int:courses_id>", views.admininfo, name="admininfo"),
    path("c_chance/<int:courses_id>", views.c_chance, name="c_chance"),
]

university/urls.py
from django.urls.conf import include
import users
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('courses/', include('courses.urls')),
    path('users/', include('users.urls')),
    path('', include('users.urls')),
]

users/urls.py
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("courses", views.index, name="index"),
]

courses/models.py
from django.db.models.deletion import CASCADE
import courses
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Courses(models.Model):
    course_code = models.CharField(max_length=2, blank=True)
    faculty = models.CharField(max_length=64)
    name = models.CharField(max_length=64)
    courses_id = models.IntegerField()
    semester = models.IntegerField()
    year = models.IntegerField()
    credit = models.IntegerField()
    remain = models.IntegerField()
    seatquota = models.IntegerField()

    def isfull(self):
        if self.remain == 0:
            return True
        return False

    def __str__(self):
        return f"{self.course_code} {self.courses_id}"


class Student(models.Model):
    student_id = models.IntegerField()
    student_user = models.OneToOneField(User, on_delete=models.CASCADE)
    student_courses = models.ManyToManyField(
        Courses, blank=True, related_name="student_courses")
    student_temp = models.ManyToManyField(
        Courses, blank=True, related_name="student_temp")

    def __str__(self):
        return f"{self.student_id} {self.student_user}"

users/models.py
from django.db import models

# Create your models here.

courses/views.py
import courses
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages

# Create your views here.

from .models import Courses, Student


def index(request):
    student = Student.objects.get(student_user=request.user)
    temp = []
    allcourses = []

    for course in Courses.objects.all():
        if (course not in student.student_courses.all()) and (course not in student.student_temp.all()):
            allcourses.append((course, course.isfull()))
        if (course in student.student_temp.all()) or (course in student.student_courses.all()):
            temp.append(course)

    return render(request, "courses/index.html", {
        "allcourses": allcourses,
        "temp": temp,
    })


def register(request, courses_id):
    if not request.user.is_authenticated:
        messages.warning(request, "Please Login")
        return HttpResponseRedirect(reverse("users:login")+f"?next={request.path}")

    course = Courses.objects.get(courses_id=courses_id)
    student = Student.objects.get(student_user=request.user)
    student.student_temp.add(course)
    student.save()
    course.remain -= 1
    course.save()

    return HttpResponseRedirect(reverse("courses:index"))


def remove(request, courses_id):
    course = Courses.objects.get(courses_id=courses_id)
    student = Student.objects.get(student_user=request.user)
    student.student_temp.remove(course)
    student.student_courses.remove(course)
    student.save()
    course.remain += 1
    course.save()

    return HttpResponseRedirect(reverse("courses:index"))


def mycourses(request):
    student = Student.objects.get(student_user=request.user)

    return render(request, "courses/mycourses.html", {
        "student_courses": student.student_courses.all()
    })


def coursesinfo(request, courses_id):
    courses_info = Courses.objects.get(courses_id=courses_id)

    return render(request, "courses/coursesinfo.html", {
        "courses_info": courses_info,
        "check": courses_info.isfull(),
    })


def confirm(request):
    student = Student.objects.get(student_user=request.user)

    for course in student.student_temp.all():
        student.student_courses.add(course)
        student.student_temp.remove(course)

    student.save()

    return render(request, "courses/confirm.html", {
        "c_courses": student.student_courses.all()
    })


def admin(request):
    return render(request, "courses/admin.html", {
        "allcourses": Courses.objects.all()
    })


def admininfo(request, courses_id):
    courses_info = Courses.objects.get(courses_id=courses_id)
    student = Student.objects.all()
    student_name = []
    student_last = []

    for i in student:
        for j in i.student_courses.all():
            if j == courses_info:
                student_name.append(i.student_user.first_name)
                student_last.append(i.student_user.last_name)

    return render(request, "courses/admin_info.html", {
        "courses_info": courses_info,
        "student_name": student_name,
        "student_last": student_last,
        "check": courses_info.isfull(),
    })


def c_chance(request, courses_id):
    courses = Courses.objects.get(courses_id=courses_id)

    if(courses.isfull()):
        courses.remain = courses.seatquota
    else:
        courses.remain = 0

    courses.save()

    return HttpResponseRedirect(reverse("courses:index"))

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

# Create your views here.


def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    else:
        return render(request, "users/index.html")


def login_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:index"))

    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("users:index"))
        else:
            messages.warning(request, "Invalid credential.")
            return render(request, "users/login.html", {"messages": messages.get_messages(request)})
    return render(request, "users/login.html")


def logout_view(request):
    logout(request)
    messages.success(request, "Logged out.")
    return render(request, "users/login.html", {
        "messages": messages.get_messages(request)
    })

courses/templates/courses/admin.html
{% extends "courses/layout.html" %}
{% load static %}
{% block body %}

<style>
    body {
        background-image: url("{% static 'images/admin.jpg' %}");
        background-attachment: fixed;
        background-size: cover;
        background-position: 0%;
    }
</style>

    <div style="font-family: 'Hammersmith One', sans-serif;"><b class="button6">All courses</b></div>
    <br>
    <br><b><i><u>
                {% for course in allcourses %}
                <li>
                    <a href="{% url 'courses:admininfo' course.courses_id %}">{{course}}</a>
                </li>
                {% endfor %}
    </b></i></u>
    <br>
    <a href="{% url 'users:index'%}"><button class="button4">Home</button></a>

{% endblock %}

courses/templates/courses/admin_info.html
{% extends "courses/layout.html" %}
{% load static %}
{% block body %}

<style>
    body {
        background-image: url("{% static 'images/admin_info.jpg' %}");
        background-attachment: fixed;
        background-size: cover;
        background-position: 0%;
    }
</style>

    <h1>
        <div style="font-family: 'Hammersmith One', sans-serif;" class="button6"><b>{{courses_info.course_code}}{{courses_info.courses_id}}</b></div>
    </h1>
    <ul style="color: rgb(0, 0, 0); font-size: 18px; font-family: 'Hammersmith One', sans-serif;">
        <li>Faculty        : {{courses_info.faculty}}</li>
        <li>Courses name   : {{ courses_info.name }}</li>
        <li>Courses id     : {{ courses_info.courses_id }}</li>
        <li>Unit of credit : {{courses_info.credit}}</li>
        <li>Semester       : {{ courses_info.semester}}/{{courses_info.year}}</li>
        <li>Available      : {{ courses_info.remain }}/{{courses_info.seatquota}}</li>
        <li>Status :
        {% if check %}
            <b style = "color: rgb(177, 31, 31);">CLOSE</b>
        {% else %}
            <b style = "color: rgb(35, 131, 35);">OPEN</b>
        {% endif %}
        </li>
    </ul>

    <h2>
        <div style="font-family: 'Hammersmith One', sans-serif;" class="button6"><b>Student names</b></div>
    </h2>
    <div style="font-family: 'Hammersmith One', sans-serif;font-size: 18px;">
        <ul style="color: rgb(0, 0, 0);">
            {%for name in student_name %}
            <li>
                {{name}}
            {%endfor%}
            
            {%for last in student_last %}
                {{last}}
            </li>
            {%empty%}
            <li>
                No student in course.
            </li>
            {%endfor%}
        </ul>
    </div>
    
    <a href="{% url 'courses:admin'%}"><button class="button4">BACK</button></a>
    {% endblock %}

courses/templates/courses/confirm.html
{% extends "courses/layout.html" %}
{% load static%}
{% block body %}

    <style>
        body{
            background-image: url("{% static 'images/confirm.jpg' %}");
            background-attachment: fixed;
            background-position:0vmin;
            background-size: cover;
        }
    </style>

    <h1><b>ENROLLMENT RESULT</b></h1> 
    <br>
    {% for c in c_courses %}
        <li>
            <b>{{c}}</b>
        </li>
    {% empty %}
            <li>
                <b>Empty enrollment.</b>
            </li>
    {% endfor %}
    <a style="margin-top:5%;" href="{% url 'users:index'%}"><button class="button1">HOME</button></a>
{% endblock %}

courses/templates/courses/coursesinfo.html
{% extends "courses/layout.html" %}
{% load static %}
{% block body %}

<style>
    body{
        background-image: url("{% static 'images/coursesinfo.jpg' %}");
        background-attachment: fixed;
        background-position:0vmin;
        background-size: cover;
    }
</style>

    <h1 style="font-family: 'Hammersmith One', sans-serif;"><b class="button6">{{courses_info.course_code}}{{courses_info.courses_id}}</b></h1>
    <div style="font-family: 'Hammersmith One', sans-serif;font-size: 18px;"><ul>
        <li>Faculty        : {{courses_info.faculty}}</li>
        <li>Courses name   : {{ courses_info.name }}</li>
        <li>Courses id     : {{ courses_info.courses_id }}</li>
        <li>Unit of credit : {{courses_info.credit}}</li>
        <li>Semester       : {{ courses_info.semester}}/{{courses_info.year}}</li>
        <li>Available      : {{ courses_info.remain }}/{{courses_info.seatquota}}</li>
        <li>Status          : 
        {% if check %}
            <b style = "color: rgb(177, 31, 31);">CLOSE</b>
        {% else %}
            <b style = "color: rgb(35, 131, 35);">OPEN</b>
        {% endif %}
        </li>
    </ul></div>
    <a href="{% url 'courses:index'%}"><button class="button4">BACK</button></a>

{% endblock %}

courses/templates/courses/index.html
{% extends "courses/layout.html" %}
{% load static%}
{% block body %}

<style>
    body{
        background-image: url("{% static 'images/courses_index.jpg' %}");
        background-attachment: fixed;
        background-position:0vmin;
        background-size: cover;
    }
</style>

    <h1><b>COURSES</b></h1>
    <br>
    <table>
            {% for c, check in allcourses %}
            <tr>
                <td><b>{{ c }}<b></td>
                <td> &emsp;<a href="{% url 'courses:coursesinfo' c.courses_id %}"><b><i><u>INFO</u></i></b></a></td>
                <td> &emsp;STATUS: {% if check %}
                    <b style = "color :rgb(177, 31, 31)">CLOSE</b>
                    <td> &emsp;&emsp;<button class = "button1 disabled">Register</button></td>
                    {% if request.user.is_superuser %}
                    <td><a href="{% url 'courses:c_chance' c.courses_id %} "><button class="button7">OPEN</button></a></td>
                    {% endif %}
                    {% else %}
                    <b style = "color : rgb(35, 131, 35)">OPEN</b>
                    <td> &emsp;&emsp;<a href="{% url 'courses:register' c.courses_id %}"><button class = "button1">Register</button></a></td>
                    {% if request.user.is_superuser %}
                    <td><a href="{% url 'courses:c_chance' c.courses_id %}"><button class="button8">CLOSE</button></a></td>
                    {% endif %}
                    {% endif %}
                 </td>
            </tr>
            {% endfor %}
    </table>    
    {% if allcourses|length == 0 %}
        No enrollment left.
    {%endif%}
    <br>
    <h1><b>REGISTRATION</b></h1>
    <br>
    <u2>
        {% for book in temp %}
            <ul>
                <b>{{ book }}</b>
            &emsp;
            <a href="{% url 'courses:remove' book.courses_id %}"><b style="color: rgb(177, 31, 31);"><i><u>REMOVE</b></i></u></a>
            </ul>
            {% empty %}
            <ul style="font-family: 'Hammersmith One', sans-serif;font-size: 20px;">
                No enrollments.
            </ul>
        {% endfor %}
    </u2>
    <br>
    <br>
    <ul>
    <a href="{% url 'users:index'%}"><button class="button4">BACK</button></a>
    <a href="{% url 'courses:confirm'%}"><button class="button1">Confirm</button></a>
    </ul>
{% endblock %}

courses/templates/courses/layout.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Courses list</title>
        <link rel="stylesheet" href="{% static 'styles/styles.css' %}"/>
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inconsolata">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Hammersmith+One&display=swap" rel="stylesheet">
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

courses/templates/courses/mycourses.html
{% extends "courses/layout.html" %}
{% load static %}
{% block body %}

<style>
    body{
        background-image: url("{% static 'images/mycourses.jpg' %}");
        background-attachment: fixed;
        background-position:0vmin;
        background-size: cover;
    }
</style>

    <h1 style="font-family: 'Hammersmith One', sans-serif;"><b class="button6">COURSES</b></h1>
    <ul>
    <br>
        {% for mycourses in student_courses %}
            <li><b style="font-size: 16px;">
            {{ mycourses }}
            </b></li>
        {% empty %}
            <li style="font-family: 'Hammersmith One', sans-serif;font-size: 18px;">
                Empty enrollment.
            </li>
        {% endfor %}
    </ul>
    <br>
    <br>

    <a href="{% url 'users:index'%}"><button class="button4">BACK</button></a>

{% endblock %}

users/templates/users/index.html
{% extends "users/layout.html" %}
{% load static %}
{% block body %}

<style>
    body{
        background-image: url("{% static 'images/users_index.jpg' %}");
        background-attachment: fixed;
        background-position:0vmin;
        background-size: cover;
    }
</style>
<div style="align-items: center;">
    <h1><b style="font-size: 60px;">Welcome, {{ request.user.first_name }}</b></h1>

    <br>

    <ul>
      <div style="font-size: 20px;font-family: 'Hammersmith One', sans-serif;">
        <li>Username: {{ request.user.username }}</li>
        <li>Email: {{ request.user.email }}</li>
      </div>
    </ul>
    <br>
</div>

<ul>
      <a href="{% url 'courses:index' %}"><button class = "button3">REGISTER</button></a> &emsp;
      <a href="{% url 'courses:mycourses' %}"><button class = "button3">MY COURSES</button></a>
      <br>
</ul>

<div class="w3-top">
  <div class="w3-row w3-padding w3-black">
    <div class="w3-col s3">
      <p class="w3-block w3-black"></p>
    </div>
    <div class="w3-col s3">
      <p class="w3-block w3-black"></p>
    </div>
    <div class="w3-col s3">
      <p class="w3-block w3-black"></p>
    </div>
    <div class="w3-col s3">
      <a href="{% url 'users:logout' %}" class="w3-button w3-block w3-black"><b>LOG OUT</b></a>
    </div>
  </div>
</div>
    
{% if request.user.is_superuser %}
    <div class="w3-top">
        <div class="w3-row w3-padding w3-black">
          <div class="w3-col s3">
            <p class="w3-block w3-black"></p>
          </div>
          <div class="w3-col s3">
            <a href="{% url 'admin:index' %}" class="w3-button w3-block w3-black"><b>ADMIN</b></a>
          </div>
          <div class="w3-col s3">
            <a href="{% url 'courses:admin'%}" class="w3-button w3-block w3-black"><b>COURSES</b></a>
          </div>
          <div class="w3-col s3">
            <a href="{% url 'users:logout' %}" class="w3-button w3-block w3-black"><b>LOG OUT</b></a>
          </div>
        </div>
    </div>
{% endif %}

{% endblock %}

users/templates/users/layout.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Users</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'styles/styles.css' %}"/>
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inconsolata">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Hammersmith+One&display=swap" rel="stylesheet">
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

users/templates/users/login.html
{% extends 'users/layout.html' %}
{% load static%}
{% block body %}

<style>
    body{
        background-image: url("{% static 'images/users_login.jpg' %}");
        background-attachment: fixed;
        background-position:0%;
        background-size: cover;
    }
</style>

	{% if messages %}
        {% for message in messages %}
        <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
        {% endfor %}
    {% endif %}

<h2></h2>
<div class="container" id="container">
	<div class="form-container sign-in-container">
		<form action="{% url 'users:login' %}" method="post">
			{% csrf_token %}
			<h1>Sign in</h1>
			<br>
			<input type="text" name="username" placeholder="Username">
			<br>
			<input type="password" name="password" placeholder="Password">
			<br>
			<button class="button">Sign In</button>
		</form>
	</div>
	<div class="overlay-container">
		<div class="overlay">
			<div class="overlay-panel overlay-right">
				<h1><b>Hello, Student!</b></h1>
				<p>Enter your courses and start journey with us</p>
			</div>
		</div>
	</div>
</div>

{% endblock %}